### ISSUE TITLE
Add docker-compose support

### ISSUE THREAD

**Issue by rmeissn** [ncarlier/webhookd#19]
Many thanks for the great image and software!

It would be extremely handy for me to not only use docker but also docker-compose in scripts executed by the service. I've spotted an appropriate package for apk - https://pkgs.alpinelinux.org/package/edge/testing/x86/docker-compose - providing docker-compose. Would be great if docker-compose could be added to this image!

EDIT: alternatively use the instructions from the alpine wiki to install pip and docker-compose - https://wiki.alpinelinux.org/wiki/Docker

**Comment by jwillmer** [comment]
Oh, sorry, I had the impression that u were looking for a demo configuration of a docker-compose file. Should have read you whole question :(

**Comment by rmeissn** [comment]
That's still handy, but yeah, my question is about adding an executable script to your image to ease docker container deployment ;)

**Comment by jwillmer** [comment]
I added docker-compose now to the image. This way you can call it inside of the image.

**Comment by jwillmer** [comment]
For reference, i mount the image in docker-compose like this:
```
    webhookd:
        hostname: webhookd
        # build: ~/repos/webhookd/.
        image: ncarlier/webhookd:latest
        container_name: webhookd
        restart: always
        networks:
            - default
        ports:
            - "8080:8080"
        environment:
            - APP_SCRIPTS_DIR=/scripts
            - APP_HOOK_TIMEOUT=60
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ~/docker/webhookd/scripts:/scripts
            - ~/docker/webhookd/logs:/tmp
            - ~/repos/demo/docker-compose.yml:/docker-compose.yml
```
and i call docker-compose like this in my script: `docker-compose -p demo up -d`

Note the folder name **demo** that I add to the docker-compose call.
