### ISSUE TITLE
"hook not found"

### ISSUE THREAD

**Issue by Berndinox** [ncarlier/webhookd#35]
GET https://hook.PRIVATEDOMAIN.at/
`{"name":"webhookd","version":""}`

GET https://hook.PRIVATEDOMAIN.at/echo
`hook not found`

Same from within the container:
```
bash-5.0# curl localhost:8080
{"name":"webhookd","version":""}bash-5.0#
bash-5.0# curl localhost:8080/echo
hook not found
bash-5.0#
```

Check everything is in place:
```
bash-5.0# ls
echo.sh     examples    execute.sh
bash-5.0# cat echo.sh
#!/bin/bash

# Usage: http POST :8080/echo msg==hello foo=bar

echo "Echo script:"

echo "Command result: hostname=`hostname`"

echo "Header variable: User-Agent=$user_agent"

echo "Query parameter: msg=$msg"

echo "Body payload: $1"
bash-5.0# pwd
/var/opt/webhookd/scripts
bash-5.0#
```
LGTM

Kubernetes YAML:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/acme-challenge-type: dns01
    cert-manager.io/acme-dns01-provider: cloudflare
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'
  name: webhook
  namespace: webhook
spec:
  rules:
  - host: hook.PRIVATEDOMAIN.at
    http:
      paths:
      - backend:
          serviceName: webhook
          servicePort: 8080
  tls:
  - hosts:
    - hook.PRIVATEDOMAIN.at
    secretName: tls-webhook
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webhook
  name: webhook
  namespace: webhook
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: webhook
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook
  namespace: webhook
  labels:
    app: webhook
spec:
  selector:
    matchLabels:
      app: webhook
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webhook
    spec:
      containers:
      - name: webhook
        image: berndinox/webook
        imagePullPolicy: Always
```
Dockerfile:
```
FROM ncarlier/webhookd
RUN apk update && apk upgrade && \
    apk add --no-cache git wget
COPY execute.sh /var/opt/webhookd/scripts
```
... not very complex.

Container-Logs:
```
INF 2020/07/25 11:37:14.085990 9f8085841545355c0a603799554e9eea GET /echo 10.0.0.210:43724 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36 63.099µs
ERR 2020/07/25 11:37:14.085942 Script not found: scripts/echo.sh
```

.. am i missing something?

**EDIT**
YEP.. fixed it:

```
        env:
        - name: WHD_SCRIPTS
          value: "/var/opt/webhookd/scripts"
```

**Comment by Berndinox** [comment]
For reference, here is the full Kubernetes deploymant:


```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webhook
  name: webhook
  namespace: webhook
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: webhook
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook
  namespace: webhook
  labels:
    app: webhook
spec:
  selector:
    matchLabels:
      app: webhook
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webhook
    spec:
      containers:
      - name: webhook
        image: ncarlier/webhookd
        imagePullPolicy: Always
        env:
        - name: WHD_SCRIPTS
          value: "/var/opt/webhookd/scripts"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/acme-challenge-type: dns01
    cert-manager.io/acme-dns01-provider: cloudflare
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'
  name: webhook
  namespace: webhook
spec:
  rules:
  - host: hook.DOMAIN.at
    http:
      paths:
      - backend:
          serviceName: webhook
          servicePort: 8080
  tls:
  - hosts:
    - hook.DOMAIN.at
    secretName: tls-webhook
```

REQ: Nginx-Ingress Controller & Cert-Manager
