### ISSUE TITLE
Docker compose issue: webhookd error message: "/docker-entrypoint.sh: exec: line 20: webhookd --scripts=/var/opt/webhookd/scripts: not found" while using docker compose with command.

### ISSUE THREAD

**Issue by Lounarok** [ncarlier/webhookd#46]
Firstly, thanks you for creating this handy container. It help a lot when I just want a webhook daemon.

However when I translate your example docker run script to docker-compose, I encounter the error message:
"/docker-entrypoint.sh: exec: line 20: webhookd --scripts=/var/opt/webhookd/scripts: not found"

My test docker compose file:
```
version: '3'
services:
    webhookd:
        container_name: webhookd
        image: ncarlier/webhookd
        volumes:
            - ${PWD}/scripts:/scripts
        command:
            - webhookd --scripts=/var/opt/webhookd/scripts

        ports:
            - '37564:8080'
```

I tried following command but is doesn't workd.
`command: /usr/local/bin/webhookd --scripts=/var/opt/webhookd/scripts`
ErrMsg is  "/docker-entrypoint.sh: exec: line 20: /usr/local/bin/webhookd --scripts=/var/opt/webhookd/scripts: not found"

However, if I remove command and add a new entry point, _it works_.
`entrypoint: /docker-entrypoint.sh webhookd --scripts=/var/opt/webhookd/scripts`

I don't get the difference between webhookd's preset entrypoint `/docker-entrypoint.sh` with `command` and my workaround..
Need your insight for this question. 

Thanks,
Louis

----
Environment ( if it matters )
Kubuntu 20.04

Webhookd --version: ( it seems version number is not displayed.. )
webhookd    | Version:    
webhookd    | Git commit: 6b3623f
webhookd    | Built:      Sun Jul 11 11:17:07 UTC 2021
