### ISSUE TITLE
webhookd has no permission for accessing /var/run/docker.sock

### ISSUE THREAD

**Issue by bastianh** [ncarlier/webhookd#76]
Hi,

when trying to access docker from within the script it fails with:

```
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json": dial unix /var/run/docker.sock: connect: permission denied
error: exit status 1
```

Thanks for your work.

**Comment by bastianh** [comment]
as a workaround you can, if using docker-compose run the webhookd in the docker group.

for example if the docker group is 124 on your host:
```
services:
  webhookd:
    hostname: webhookd
    user: 1000:124
    image: ncarlier/webhookd:edge-distrib
```
